### ISSUE TITLE
Bug: Neighbor city has more than 100% shares floated, not selling shares

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#413]
` The Mounds is located to the northeast of your arcology. It is governed by direct democracy, making its development dangerously unstable. Its leadership has control of approximately 58% of the arcology. You own 49% of this arcology The arcology has an estimated GSP of ¤0m, behind its neighbors. `

It seems like they should have sold off ages ago.  It also seems like 58 + 49 is more than 100.  Something wonky here.

[mounds neighbor city broken amount of shares.zip](https://github.com/Free-Cities/Free-Cities/files/981331/mounds.neighbor.city.broken.amount.of.shares.zip)

**Comment by DrNoOne0** [comment]
I just made a pull that should fix this.  Just a note though, the 58% that is listed is intentionally not accurate.  In your save file the actual value is 51% (can be tested by selling and buying shares).  The actual problem here is that if 100% of shares are split between current leadership and the PC, no shares will become available unless the PC has more than leadership and can thus take control of the arcology.

**Comment by lowercase-donkey** [comment]
@freecitiesdev  @DrNoOne0 

Looks like people are grumbling about this on reddit again, mind taking a look?

https://www.reddit.com/r/freecitiesgame/comments/6m5vya/bug_when_taking_over_opponent_arcologies/

**Comment by kopareigns** [comment]
I'm about 90% sure I fixed that last quirk in #815

**Comment by lowercase-donkey** [comment]
Looks  like you fixed it to me. I don't happen to have a save to help you test though.  Probably fixed then. Thanks!
