### ISSUE TITLE
Closing tag mismatch, causing problems in slave summary

### ISSUE THREAD

**Issue by Clegane32** [Free-Cities/Free-Cities#733]
The Errors are "<<if $abbreviateDiet==1>..." and "<<elseif $abbreviateDiet==2>..."

e.g.
 Worshipful [100]. Profoundly trusting [95]. Living standard: luxurious. Relationship rules: permissive. Typical punishment: situational. Typical reward: situational. Release rules: restrictive. Error: cannot find a closing tag for macro <<if>> W+++[100] Error: child tag <<elseif>> was found outside of a call to its parent macro <<if>> Dieting. Diet Bas

Occurs with a fresh start, and 2 saves

**Comment by Boney-M** [comment]
That was my fault, I missed an /if on line 793. It's fixed in #730 

If you want to test the latest before the fixes get merged in - FC Dev usually doesn't work on the game on the weekend - I've got it built into the master branch of my fork, along with the emotional slut fix in #728 - https://github.com/Boney-M/Free-Cities

**Comment by Clegane32** [comment]
I just fixed it (the "/if") on my own fork and was about to commit. When I read this message.
