### ISSUE TITLE
Blank Events

### ISSUE THREAD

**Issue by eldestdawn** [Free-Cities/Free-Cities#765]
Attached is a save with a blank event. There is nothing there but one can still proceed to the next event by normal means.
[free-cities-20170623-083044.zip](https://github.com/Free-Cities/Free-Cities/files/1098315/free-cities-20170623-083044.zip)

I have come across it multiple times but there doesn't seem to be anything else happening other than skipping an unknown event.

**Comment by Boney-M** [comment]
From the 'inspect' button, it looks like it's hanging on REFS. The applicable FSs in your game would be Paternalist, Body Purist, and Pastoralist. Maybe one of those is bugged - I've had the Body Purist REFS event trigger in my games, has anyone seen the other two?

**Comment by tc-k** [comment]
Hmmm, I downloaded his savegame and turned on the cheatmode and was able to try all three REFS and all three fired just fine.

**Comment by goldifrocks** [comment]
this happens if $REFSevent being an array (REFS.tw):

`<<if Array.isArray($REFSevent)>>
event selection (automatic/manual with cheat mode)
<<else>>
the actual events
<</if>> /* CLOSES EVENT SELECTION */`

in the end, if your arcology is eligible for multiple REFS events and these want to fire, REFS gets stuck in event selection.

**Comment by freecitiesbandit** [comment]
Hm, did I do something wrong when I was setting REFS up?

**Comment by kopareigns** [comment]
I see it now. When REFS is first loaded, $REFSevent is always an array so you always end up in the first part of the if statement goldifrocks pointed out (so the events don't display yet). There's a second check in there for cheatmode. If cheatmode is off, $REFSevent is set to a single random element of the array. But REFS is not reloaded. To mimic the other event files, the fix is just putting
`<<goto "REFS">>`
immediately after
`<<set $REFSevent = $REFSevent.random()>>`
in that opening if statement.
