### ISSUE TITLE
Strange conflict between nobr standardization and compiler

### ISSUE THREAD

**Issue by freecitiesdev** [Free-Cities/Free-Cities#941]
As referenced in #940.

When applied, #918 causes the compiler to complain about art widgets. It then seems to revert all subsequent work to artWidgets.tw, reverting #932 for example.

**Comment by lowercase-donkey** [comment]
I believe I address this in #945.

Short version, due to some newline shenanigans, git was squawking, and there were briefly two separate artWidget files, one in the old `utility` location and one in the new `art` location.

#943 removes the copy from the older location, and adds the polish back to outfits.

**Comment by freecitiesdev** [comment]
Closing.
