### ISSUE TITLE
Repeating:  "tries to strike up a sexual relationship with X and is punished for breaking the rules against such things"

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#974]
Slave reallllllly wants a friend.

 

> Zhi tries to strike up a sexual relationship with Hafida and is punished for breaking the rules against such things; she resents being prevented from pursuing her. Zhi tries to strike up a sexual relationship with Qaisara and is punished for breaking the rules against such things; she resents being prevented from pursuing her. Zhi tries to strike up a sexual relationship with Vika and is punished for breaking the rules against such things; she resents being prevented from pursuing her. Zhi tries to strike up a sexual relationship with Marilyn and is punished for breaking the rules against such things; she resents being prevented from pursuing her. Zhi tries to strike up a sexual relationship with Zahra and is punished for breaking the rules against such things; she resents being prevented from pursuing her. 

Seems like the game just keeps trying after it's told 'no,' and I'm worried about the cascading resentment.  This is a slave resting in the spa.

[free-cities-20170816-020410.zip](https://github.com/Free-Cities/Free-Cities/files/1227187/free-cities-20170816-020410.zip)

**Comment by prndev** [comment]
In prndev/Free-Cities@fbf6690 I tried to fix this by inserting a break statement in an appropriate position. Now the search for friends does not ever seem to occur at all. No pull request as I seem to be missing something.

**Comment by pregAnon** [comment]
I've watched this for several months without any real luck in culling it. I'm thinking that making a sub-array of potential targets, shuffling it, then reducing it in size could be a solution.
Break statements would just ruin the randomness of it by stopping it after the first potential target in the slave array, so that's not an option
Also recent reports have come in about the same thing occuring with rivals.
